### ISSUE TITLE
Node colors does not work for large graphs on Jupyter/IJulia

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [JuliaGraphs/GraphPlot.jl#62] opened 2018-05-31 20:44 UTC
I'm looking at a version of the connectome("neural wiring") of the C. elegans worm, a graph of 297 vertices.  I'm trying to display the graph with each vertex colored according to it's eccentricity, with more central vertices in a hotter color.

However, `gplot()` colors each node black, even with the `nodefillc` parameter assigned.  It seems that this is an issue with plotting large graphs.  Test code, adapted from the documentation:
```
using LightGraphs
using GraphPlot

n=195
g=erdos_renyi(n,.05)
membership=rand([1,2], nv(g));
nodecolor = [colorant"lightseagreen", colorant"orange"]
nodefillc = nodecolor[membership]
gplot(g, nodefillc=nodefillc)
```

When `n` is larger than 195, the nodes are all filled in black, as opposed to green and orange.

**Comment by sbromberger** [comment] 2018-05-31 21:27
I'm unable to reproduce (your code with `n=300`):

![screen shot 2018-05-31 at 14 28 56](https://user-images.githubusercontent.com/941359/40809266-c31e6c0c-64de-11e8-8225-a2d6ecaaa509.png)

**Comment by Jacob-Stevens-Haas** [comment] 2018-05-31 22:05
Thanks for the quick reply.  How interesting.  Are you using something other than the `Colors` package?  I added it to the previous post.  Here's the images I'm getting, FYI:
`n=150`
![colored](https://user-images.githubusercontent.com/37048747/40810656-5038548c-64e3-11e8-99cd-817825751e9e.PNG)
`n=300`
![notcolored](https://user-images.githubusercontent.com/37048747/40810659-517e2dbc-64e3-11e8-9394-fffb1af1a7fa.PNG)

Interestingly, when I use the other example from the documentation:
`nodefillc = distinguishable_colors((g), colorant"blue")`
it seems to work:
![verycolored](https://user-images.githubusercontent.com/37048747/40810660-52d2a2ba-64e3-11e8-9c7d-76752e781bfc.PNG)
In both cases, `typeof(nodefillc)` returns `Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},1}`.  They're both length 300.

**Comment by sbromberger** [comment] 2018-05-31 22:09
> Are you using something other than the Colors package? 

Not that I'm aware.

I was doing this within vscode, so maybe that makes a difference?

**Comment by Jacob-Stevens-Haas** [comment] 2018-06-01 00:45
Struggling to get plots working in Juno.  Can GraphPlot work as a backend to Plots.jl?  I see your examples on other issues reference Compose.jl, rather than Plots.jl

**Comment by sbromberger** [comment] 2018-07-17 16:47
Since this isn't specific to gplot, I think we can close this out. It's more likely some bug in jupyter/ijulia or some strange edge case. Let me know if you'd like to continue troubleshooting and I'm happy to reopen.

**Closed by sbromberger** 2018-07-17 16:47 UTC

**Comment by dmos62** [comment] 2020-05-06 17:28
Can still reproduce. Also unsure where the cause is. I've a new clue though. Currently I'm rendering to file as a workaround, but I've noticed that if I render the same plot object (the return value of `gplot(...)` call) more than once, after the first time the nodes will be colored black. Using JupyterLab.

My snippet:

```
p = gplot(sg, nodefillc=nodefillc);
draw(SVG("plot.svg", 50cm, 50cm), p);
```
